"""Initial migration with all current models

Revision ID: 550facfb6d88
Revises: 
Create Date: 2025-11-21 07:47:56.145954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550facfb6d88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('marketing_expenses', sa.Float(), nullable=True),
    sa.Column('advance_expenses', sa.Float(), nullable=True),
    sa.Column('aggregator', sa.String(), nullable=True),
    sa.Column('yoga', sa.String(), nullable=True),
    sa.Column('Zaycev', sa.String(), nullable=True),
    sa.Column('additional_sites', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isni', sa.String(), nullable=True),
    sa.Column('marketing_expenses', sa.Float(), nullable=True),
    sa.Column('advance_expenses', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isni')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('marketing_expenses', sa.Float(), nullable=True),
    sa.Column('advance_expenses', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('record_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('album_artist',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'artist_id')
    )
    op.create_table('artistperson',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'person_id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('isrc', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('label_share_percentage', sa.Float(), nullable=False),
    sa.Column('scope_of_copyright', sa.Float(), nullable=True),
    sa.Column('scope_of_related_rights', sa.Float(), nullable=True),
    sa.Column('neighboring_rights_share', sa.Float(), nullable=True),
    sa.Column('label_rights_share', sa.Float(), nullable=True),
    sa.Column('label_monetization_share', sa.Float(), nullable=True),
    sa.Column('marketing_expenses', sa.Float(), nullable=True),
    sa.Column('advance_expenses', sa.Float(), nullable=True),
    sa.Column('is_ringtone_added', sa.Boolean(), nullable=False),
    sa.Column('has_video_clip', sa.Boolean(), nullable=False),
    sa.Column('is_lyrics_added', sa.Boolean(), nullable=False),
    sa.Column('is_karaoke_sync_added', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('karaoke', sa.String(), nullable=True),
    sa.Column('synclab', sa.String(), nullable=True),
    sa.Column('copyright', sa.String(), nullable=True),
    sa.Column('related_rights', sa.String(), nullable=True),
    sa.Column('advance', sa.String(), nullable=True),
    sa.Column('marketing', sa.String(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['record_label.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc')
    )
    op.create_table('track_person_share',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('share_of_monetization_of_copyrights', sa.Float(), nullable=False),
    sa.Column('share_of_monetization_of_related_rights', sa.Float(), nullable=False),
    sa.Column('copyrights', sa.Float(), nullable=False),
    sa.Column('related_rights', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'person_id')
    )
    op.create_table('trackartist',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'artist_id')
    )
    op.create_table('usage_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('right_type', sa.String(), nullable=False),
    sa.Column('territory', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('performer_name_excel', sa.String(), nullable=False),
    sa.Column('track_title_excel', sa.String(), nullable=False),
    sa.Column('album_title_excel', sa.String(), nullable=False),
    sa.Column('author_words_name_excel', sa.String(), nullable=False),
    sa.Column('author_music_name_excel', sa.String(), nullable=False),
    sa.Column('licensor_share_author_percent', sa.Float(), nullable=False),
    sa.Column('licensor_share_neighboring_percent', sa.Float(), nullable=False),
    sa.Column('isrc', sa.String(), nullable=False),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('copyright', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_royalty_author', sa.Float(), nullable=False),
    sa.Column('total_royalty_neighboring', sa.Float(), nullable=False),
    sa.Column('licensor_share_overall_percent', sa.Float(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.Column('author_words_id', sa.Integer(), nullable=True),
    sa.Column('author_music_id', sa.Integer(), nullable=True),
    sa.Column('calculated_royalty_author', sa.Float(), nullable=True),
    sa.Column('calculated_royalty_neighboring', sa.Float(), nullable=True),
    sa.Column('calculated_total_royalty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['author_music_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['author_words_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_report')
    op.drop_table('trackartist')
    op.drop_table('track_person_share')
    op.drop_table('track')
    op.drop_table('artistperson')
    op.drop_table('album_artist')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('record_label')
    op.drop_table('person')
    op.drop_table('artist')
    op.drop_table('album')
    # ### end Alembic commands ###