"""Make right_type nullable in usage_report

Revision ID: 9acb17fcc03a
Revises: ваш_новый_id
Create Date: 2025-11-24 03:44:04.353119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acb17fcc03a'
down_revision: Union[str, Sequence[str], None] = 'ваш_новый_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_report', 'right_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_report', 'right_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
