"""add version, subgenre, isrc, zaycev_star, synclab_star to album

Revision ID: a2bb0e864b03
Revises: 9acb17fcc03a
Create Date: 2025-12-02 01:33:30.422210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bb0e864b03'
down_revision: Union[str, Sequence[str], None] = '9acb17fcc03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('version', sa.String(), nullable=True))
    op.add_column('album', sa.Column('subgenre', sa.String(), nullable=True))
    op.add_column('album', sa.Column('isrc', sa.String(), nullable=True))
    op.add_column('album', sa.Column('zaycev_star', sa.String(), nullable=True))
    op.add_column('album', sa.Column('synclab_star', sa.String(), nullable=True))
    op.create_unique_constraint('uq_album_isrc', 'album', ['isrc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_album_isrc', 'album', type_='unique')
    op.drop_column('album', 'synclab_star')
    op.drop_column('album', 'zaycev_star')
    op.drop_column('album', 'isrc')
    op.drop_column('album', 'subgenre')
    op.drop_column('album', 'version')
    # ### end Alembic commands ###