"""Add raw_usage_data_strict table with explicit columns

Revision ID: c6ded5412a59
Revises: f9fb226f4cd2
Create Date: 2025-12-28 04:11:24.469188

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6ded5412a59'
down_revision: Union[str, Sequence[str], None] = 'f9fb226f4cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_usage_data_strict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excel_report_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('right_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performer_name_excel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('track_title_excel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_title_excel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_words_name_excel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_music_name_excel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('licensor_share_author_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('licensor_share_neighboring_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('isrc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('copyright', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_royalty_author', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_royalty_neighboring', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('licensor_share_author_licensor_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('licensor_share_neighboring_licensor_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_royalty_author', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('calculated_royalty_neighboring', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('calculated_total_royalty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('processed_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['excel_report_id'], ['excel_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_usage_data_strict_excel_report_id'), 'raw_usage_data_strict', ['excel_report_id'], unique=False)
    op.create_index(op.f('ix_raw_usage_data_strict_id'), 'raw_usage_data_strict', ['id'], unique=False)
    op.drop_index(op.f('ix_raw_usage_data_excel_report_id'), table_name='raw_usage_data')
    op.drop_index(op.f('ix_raw_usage_data_id'), table_name='raw_usage_data')
    op.drop_table('raw_usage_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_usage_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('excel_report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processed_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['excel_report_id'], ['excel_reports.id'], name=op.f('raw_usage_data_excel_report_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_usage_data_pkey'))
    )
    op.create_index(op.f('ix_raw_usage_data_id'), 'raw_usage_data', ['id'], unique=False)
    op.create_index(op.f('ix_raw_usage_data_excel_report_id'), 'raw_usage_data', ['excel_report_id'], unique=False)
    op.drop_index(op.f('ix_raw_usage_data_strict_id'), table_name='raw_usage_data_strict')
    op.drop_index(op.f('ix_raw_usage_data_strict_excel_report_id'), table_name='raw_usage_data_strict')
    op.drop_table('raw_usage_data_strict')
    # ### end Alembic commands ###
