"""Add excel_reports and raw_usage_data tables

Revision ID: f9fb226f4cd2
Revises: 54f43ed396f2
Create Date: 2025-12-28 03:34:17.302524

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9fb226f4cd2'
down_revision: Union[str, Sequence[str], None] = '54f43ed396f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('upload_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_reports_id'), 'excel_reports', ['id'], unique=False)
    op.create_table('raw_usage_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excel_report_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['excel_report_id'], ['excel_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_usage_data_excel_report_id'), 'raw_usage_data', ['excel_report_id'], unique=False)
    op.create_index(op.f('ix_raw_usage_data_id'), 'raw_usage_data', ['id'], unique=False)
    op.drop_constraint(op.f('uq_album_isrc'), 'album', type_='unique')
    op.drop_constraint(op.f('fk_album_user'), 'album', type_='foreignkey')
    op.create_unique_constraint(None, 'artist', ['isni'])
    op.drop_constraint(op.f('fk_artist_user'), 'artist', type_='foreignkey')
    op.create_unique_constraint(None, 'person', ['email'])
    op.drop_constraint(op.f('fk_person_user'), 'person', type_='foreignkey')
    op.drop_constraint(op.f('fk_track_user'), 'track', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_track_user'), 'track', 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_person_user'), 'person', 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'person', type_='unique')
    op.create_foreign_key(op.f('fk_artist_user'), 'artist', 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'artist', type_='unique')
    op.create_foreign_key(op.f('fk_album_user'), 'album', 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_album_isrc'), 'album', ['isrc'])
    op.drop_index(op.f('ix_raw_usage_data_id'), table_name='raw_usage_data')
    op.drop_index(op.f('ix_raw_usage_data_excel_report_id'), table_name='raw_usage_data')
    op.drop_table('raw_usage_data')
    op.drop_index(op.f('ix_excel_reports_id'), table_name='excel_reports')
    op.drop_table('excel_reports')
    # ### end Alembic commands ###
